assets:
  mode: whitelist
  whitelist:
  - BTC/USD
  - ETH/USD
  - SOL/USD
  - XRP/USD
  - ADA/USD
  - LINK/USD
  - DOGE/USD
  - AVAX/USD
  - LTC/USD
  - TRX/USD
  - DOT/USD
  - BCH/USD
risk:
  symbol_overrides: {}
strategy:
  symbol_overrides: {}
