#!/usr/bin/env bash
#
# Research baseline recovery watchdog:
# - Detects daemon/run drift and stalls
# - Repairs critical overrides
# - Restarts daemon when unhealthy
# - Optionally triggers targeted candle backfill for current symbol
#
set -euo pipefail

TRADING_DIR="${DEPLOY_TRADING_DIR:-/home/trading/TradingSystem}"
cd "${TRADING_DIR}"
if [[ -f ".env" ]]; then
  # shellcheck disable=SC1091
  set -a
  source .env
  set +a
fi

STATE_ROOT="data/research/continuous_daemon"
RUNS_DIR="${STATE_ROOT}/runs"
LOG_DIR="${STATE_ROOT}/logs"
PID_FILE="${STATE_ROOT}/daemon.pid"
LATEST_RUN_FILE="${STATE_ROOT}/latest_run_id"
WATCHDOG_STATE_FILE="${STATE_ROOT}/watchdog_state.json"
WATCHDOG_LOG_FILE="${LOG_DIR}/watchdog.log"
AUTOCONTEXT_OVERRIDES_FILE="${STATE_ROOT}/autocontext/overrides.env"
STOP_FILE="${STATE_ROOT}/stop_requested"

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

WATCHDOG_MAX_STATE_AGE_SECONDS="${WATCHDOG_MAX_STATE_AGE_SECONDS:-1800}"
WATCHDOG_MAX_LOG_QUIET_SECONDS="${WATCHDOG_MAX_LOG_QUIET_SECONDS:-600}"
WATCHDOG_MAX_STAGNANT_SECONDS="${WATCHDOG_MAX_STAGNANT_SECONDS:-2400}"
WATCHDOG_CANONICAL_CONVICTION="${WATCHDOG_CANONICAL_CONVICTION:-20}"
WATCHDOG_FORCE_AUTO_BACKFILL="${WATCHDOG_FORCE_AUTO_BACKFILL:-1}"
WATCHDOG_ENABLE_TARGETED_BACKFILL="${WATCHDOG_ENABLE_TARGETED_BACKFILL:-1}"
WATCHDOG_NO_CANDLES_SPIKE_THRESHOLD="${WATCHDOG_NO_CANDLES_SPIKE_THRESHOLD:-50}"
WATCHDOG_BACKFILL_BOOTSTRAP_DAYS="${WATCHDOG_BACKFILL_BOOTSTRAP_DAYS:-30}"

mkdir -p "${LOG_DIR}" "${STATE_ROOT}/autocontext"

log_msg() {
  local level="$1"
  local event="$2"
  local details="$3"
  local line
  line="[$(date -u +%FT%TZ)] [${level}] ${event} ${details}"
  echo "${line}" | tee -a "${WATCHDOG_LOG_FILE}"
}

maybe_run() {
  if [[ "${DRY_RUN}" == "1" ]]; then
    log_msg "info" "DRY_RUN_SKIP" "cmd=$*"
    return 0
  fi
  "$@"
}

repair_overrides() {
  local changes
  changes="$("${TRADING_DIR}/venv/bin/python3" - <<PY 2>/dev/null || true
from pathlib import Path

path = Path("${AUTOCONTEXT_OVERRIDES_FILE}")
path.parent.mkdir(parents=True, exist_ok=True)
text = path.read_text(encoding="utf-8") if path.exists() else ""
pairs = {}
header = []
for line in text.splitlines():
    stripped = line.strip()
    if not stripped:
        continue
    if stripped.startswith("#"):
        header.append(line.rstrip())
        continue
    if "=" in line:
        key, value = line.split("=", 1)
        pairs[key.strip()] = value.strip()

changes = []
target_auto = "${WATCHDOG_FORCE_AUTO_BACKFILL}"
if pairs.get("RESEARCH_CONT_AUTO_BACKFILL_DATA") != target_auto:
    pairs["RESEARCH_CONT_AUTO_BACKFILL_DATA"] = target_auto
    changes.append(f"RESEARCH_CONT_AUTO_BACKFILL_DATA={target_auto}")
if pairs.get("AUTO_BACKFILL_DATA") != target_auto:
    pairs["AUTO_BACKFILL_DATA"] = target_auto
    changes.append(f"AUTO_BACKFILL_DATA={target_auto}")

target_floor = float("${WATCHDOG_CANONICAL_CONVICTION}")
current_raw = pairs.get("REPLAY_OVERRIDE_CONVICTION_MIN_FOR_ENTRY")
current = None
if current_raw is not None:
    try:
        current = float(current_raw)
    except ValueError:
        current = None
if current is None or current > target_floor:
    value = str(int(target_floor) if target_floor.is_integer() else target_floor)
    pairs["REPLAY_OVERRIDE_CONVICTION_MIN_FOR_ENTRY"] = value
    changes.append(f"REPLAY_OVERRIDE_CONVICTION_MIN_FOR_ENTRY={value}")

if changes:
    out_header = header or [
        "# Auto-generated by scripts/research_autolearn.py",
        "# Format: shell variable assignments consumed by research_continuous.sh",
    ]
    body = [f"{k}={pairs[k]}" for k in sorted(pairs)]
    path.write_text("\\n".join(out_header + body) + "\\n", encoding="utf-8")
print(",".join(changes))
PY
)"

  if [[ -n "${changes}" ]]; then
    log_msg "warn" "OVERRIDE_REPAIRED" "changes=${changes} file=${AUTOCONTEXT_OVERRIDES_FILE}"
  fi
}

daemon_pid=""
daemon_running=0
if [[ -f "${PID_FILE}" ]]; then
  daemon_pid="$(cat "${PID_FILE}" 2>/dev/null || true)"
fi
if [[ -n "${daemon_pid}" ]] && kill -0 "${daemon_pid}" 2>/dev/null; then
  daemon_running=1
fi

restart_daemon() {
  local reason="$1"
  log_msg "warn" "DAEMON_RESTART_REQUESTED" "reason=${reason}"
  if [[ "${DRY_RUN}" == "1" ]]; then
    return 0
  fi
  touch "${STOP_FILE}" || true
  if [[ -n "${daemon_pid}" ]]; then
    kill "${daemon_pid}" 2>/dev/null || true
  fi
  pkill -f "run.py research --mode replay" 2>/dev/null || true
  sleep 3
  rm -f "${STOP_FILE}"
  nohup bash "${TRADING_DIR}/scripts/research_continuous.sh" >> "${LOG_DIR}/daemon.out" 2>&1 &
  sleep 2
  log_msg "info" "DAEMON_RESTARTED" "reason=${reason}"
}

maybe_targeted_backfill() {
  local symbol="$1"
  if [[ "${WATCHDOG_ENABLE_TARGETED_BACKFILL}" != "1" ]]; then
    return 0
  fi
  if [[ -z "${symbol}" ]]; then
    return 0
  fi
  log_msg "warn" "TARGETED_BACKFILL_REQUESTED" "symbol=${symbol}"
  set +e
  maybe_run "${TRADING_DIR}/venv/bin/python3" "${TRADING_DIR}/scripts/collect_kraken_candles_continuous.py" \
    --symbols "${symbol}" \
    --timeframes "15m,1h,4h,1d" \
    --bootstrap-days "${WATCHDOG_BACKFILL_BOOTSTRAP_DAYS}" \
    --once
  local rc=$?
  set -e
  if [[ "${rc}" -ne 0 ]]; then
    log_msg "warn" "TARGETED_BACKFILL_FAILED" "symbol=${symbol} rc=${rc}"
  fi
}

repair_overrides

if [[ "${daemon_running}" != "1" ]]; then
  restart_daemon "daemon_not_running"
  exit 0
fi

latest_run_id=""
if [[ -f "${LATEST_RUN_FILE}" ]]; then
  latest_run_id="$(cat "${LATEST_RUN_FILE}" 2>/dev/null || true)"
fi
if [[ -z "${latest_run_id}" ]]; then
  log_msg "warn" "MISSING_LATEST_RUN_ID" "action=restart_daemon"
  restart_daemon "missing_latest_run_id"
  exit 0
fi

state_file="${RUNS_DIR}/${latest_run_id}/state.json"
run_log="${RUNS_DIR}/${latest_run_id}/research.log"
if [[ ! -f "${state_file}" ]]; then
  log_msg "warn" "MISSING_STATE_FILE" "run_id=${latest_run_id} action=restart_daemon"
  restart_daemon "missing_state_file"
  exit 0
fi

analysis="$("${TRADING_DIR}/venv/bin/python3" - <<PY
import json
from datetime import datetime, timezone
from pathlib import Path

state_path = Path("${state_file}")
run_log = Path("${run_log}")
watchdog_state = Path("${WATCHDOG_STATE_FILE}")

loaded = json.loads(state_path.read_text())
state = loaded if isinstance(loaded, dict) else {}
now = datetime.now(timezone.utc)

updated_raw = state.get("updated_at")
updated_age = 10**9
if updated_raw:
    try:
        dt = datetime.fromisoformat(updated_raw.replace("Z", "+00:00"))
        updated_age = int((now - dt).total_seconds())
    except ValueError:
        updated_age = 10**9

log_age = 10**9
if run_log.exists():
    log_age = int(now.timestamp() - run_log.stat().st_mtime)

phase = str(state.get("phase") or "")
completed = len(state.get("completed_symbols") or [])
total = int(state.get("total_symbols") or 0)
current_symbol = str(state.get("current_symbol") or "")
sp_raw = (state.get("symbol_progress") or {}).get(current_symbol) if current_symbol else {}
sp = sp_raw if isinstance(sp_raw, dict) else {}
iteration = sp.get("iteration")
marker = f"{phase}|{completed}|{total}|{current_symbol}|{iteration}"

same_for = 0
if watchdog_state.exists():
    prev_loaded = json.loads(watchdog_state.read_text())
    prev = prev_loaded if isinstance(prev_loaded, dict) else {}
    if prev.get("marker") == marker:
        same_for = int((now.timestamp() - float(prev.get("ts", now.timestamp()))))

watchdog_state.write_text(
    json.dumps({"marker": marker, "ts": now.timestamp()}, sort_keys=True),
    encoding="utf-8",
)

tail_no_candles = 0
if run_log.exists():
    lines = run_log.read_text(errors="replace").splitlines()[-2000:]
    tail_no_candles = sum(1 for line in lines if "No candles for" in line)

print(f"phase={phase}")
print(f"completed={completed}")
print(f"total={total}")
print(f"current_symbol={current_symbol}")
print(f"updated_age={updated_age}")
print(f"log_age={log_age}")
print(f"same_for={same_for}")
print(f"tail_no_candles={tail_no_candles}")
PY
)"

phase="$(echo "${analysis}" | awk -F= '/^phase=/{print $2}')"
current_symbol="$(echo "${analysis}" | awk -F= '/^current_symbol=/{print $2}')"
updated_age="$(echo "${analysis}" | awk -F= '/^updated_age=/{print $2}')"
log_age="$(echo "${analysis}" | awk -F= '/^log_age=/{print $2}')"
same_for="$(echo "${analysis}" | awk -F= '/^same_for=/{print $2}')"
tail_no_candles="$(echo "${analysis}" | awk -F= '/^tail_no_candles=/{print $2}')"

log_msg "info" "WATCHDOG_STATUS" "run_id=${latest_run_id} phase=${phase} updated_age=${updated_age}s log_age=${log_age}s same_for=${same_for}s no_candles_tail=${tail_no_candles}"

if [[ "${tail_no_candles}" =~ ^[0-9]+$ ]] && [[ "${tail_no_candles}" -ge "${WATCHDOG_NO_CANDLES_SPIKE_THRESHOLD}" ]]; then
  maybe_targeted_backfill "${current_symbol}"
fi

if [[ "${updated_age}" =~ ^[0-9]+$ ]] && [[ "${log_age}" =~ ^[0-9]+$ ]]; then
  if [[ "${updated_age}" -ge "${WATCHDOG_MAX_STATE_AGE_SECONDS}" ]] && [[ "${log_age}" -ge "${WATCHDOG_MAX_LOG_QUIET_SECONDS}" ]]; then
    restart_daemon "state_and_log_stale"
    exit 0
  fi
fi

if [[ "${same_for}" =~ ^[0-9]+$ ]] && [[ "${same_for}" -ge "${WATCHDOG_MAX_STAGNANT_SECONDS}" ]] && [[ "${log_age}" -ge "${WATCHDOG_MAX_LOG_QUIET_SECONDS}" ]]; then
  restart_daemon "progress_stagnant"
  exit 0
fi

log_msg "info" "WATCHDOG_OK" "run_id=${latest_run_id} phase=${phase}"
