"""Tests for mini-autocontext research autolearn logic."""

from __future__ import annotations

from pathlib import Path
import importlib.util
import sys
import json


def _load_module():
    path = Path(__file__).resolve().parents[2] / "scripts" / "research_autolearn.py"
    spec = importlib.util.spec_from_file_location("research_autolearn", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def test_build_overrides_prefers_trade_active_subset() -> None:
    mod = _load_module()
    snapshot = mod.RunSnapshot(
        run_id="r1",
        phase="finished",
        completed=40,
        total_symbols=40,
        eligible=40,
        skipped=0,
        baseline_best=40,
        nonbaseline_best=0,
        skipped_insufficient_signal=0,
        skipped_uninformative_surface=0,
        replay_timeout_mentions=0,
        paused_health_mentions=0,
        fib_gate_reject_mentions=0,
        score_gate_reject_mentions=0,
        dedupe_suppressed_mentions=0,
        conviction_gate_block_mentions=0,
        thesis_reentry_block_mentions=0,
        rr_multiple_reject_mentions=0,
        opens_planned_mentions=0,
        opens_executed_mentions=0,
        top_trade_symbols=[f"S{i}/USD" for i in range(12)],
    )

    overrides = mod._build_overrides(snapshot)

    assert overrides["SYMBOLS_FROM_LIVE_UNIVERSE"] == "0"
    assert "SYMBOLS" in overrides
    assert overrides["MAX_ITERS_PER_SYMBOL"] == "160"
    assert overrides["MAX_STAGNANT_ITERS"] == "24"


def test_write_overrides_preserves_pinned_scope_keys(tmp_path: Path) -> None:
    mod = _load_module()
    overrides_file = tmp_path / "overrides.env"
    overrides_file.write_text(
        "\n".join(
            [
                "# Auto-generated by scripts/research_autolearn.py",
                "# Format: shell variable assignments consumed by research_continuous.sh",
                "SYMBOLS=BTC/USD,ETH/USD,SOL/USD,XRP/USD,ADA/USD,LINK/USD",
                "SYMBOLS_FROM_CONFIG_UNIVERSE=0",
                "UNRELATED_KEY=drop-me",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    mod._write_overrides(
        overrides_file,
        {
            "REPLAY_OVERRIDE_CONVICTION_MIN_FOR_ENTRY": "20",
            "AUTO_BACKFILL_DATA": "1",
        },
    )

    body = overrides_file.read_text(encoding="utf-8")
    assert "SYMBOLS=BTC/USD,ETH/USD,SOL/USD,XRP/USD,ADA/USD,LINK/USD" in body
    assert "SYMBOLS_FROM_CONFIG_UNIVERSE=0" in body
    assert "AUTO_BACKFILL_DATA=1" in body
    assert "REPLAY_OVERRIDE_CONVICTION_MIN_FOR_ENTRY=20" in body
    assert "UNRELATED_KEY=drop-me" not in body


def test_best_by_symbol_file_falls_back_to_nested_worker_artifacts(tmp_path: Path) -> None:
    mod = _load_module()
    nested = tmp_path / "w0_1_BTC_USD"
    nested.mkdir(parents=True)
    target = nested / "run_nested_best_by_symbol.json"
    target.write_text(json.dumps({"best_by_symbol": {"BTC/USD": {"candidate_id": "BTC_USD_c001"}}}), encoding="utf-8")

    found = mod._best_by_symbol_file(tmp_path)

    assert found == target
